apiVersion: apps/v1
kind: Deployment
metadata:
  name: digishop-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel
  template:
    metadata:
      labels:
        app: tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: digishop-secrets
              key: tunnel-token
        - name: TUNNEL_TRANSPORT_PROTOCOL
          value: "http2"
